:: initializing oneAPI environment ...
   BASH version = 4.2.46(2)-release
:: dev-utilities -- latest
:: tbb -- latest
:: compiler -- latest
:: dpl -- latest
:: mkl -- latest
:: ipp -- latest
:: mpi -- latest
:: ccl -- latest
:: vtune -- latest
:: dpcpp-ct -- latest
:: dal -- latest
:: intelpython -- latest
:: ippcp -- latest
:: debugger -- latest
:: inspector -- latest
:: clck -- latest
:: itac -- latest
:: oneAPI environment initialized ::
     using /nfsexports/SOFTWARE/intel/oneapi/mpi/2021.1.1/bin/mpirun
Using Python 3.11.7
/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
Using Materials Project MACE for MACECalculator with /lustre/home/mmollo/.cache/mace/5yyxdm76
Using float64 for MACECalculator, which is slower but more accurate. Recommended for geometry optimization.
[I] Phonon calculation for displacement: 0.0001
Traceback (most recent call last):
  File "/ibiscostorage/mmollo/99_diario/2024-01-30/01_ice_xi_phonons/10_run_supercell=6_mace/02_phonons.py", line 19, in <module>
    ph.run()
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/ase/phonons.py", line 201, in run
    result = self.calculate(atoms_N, disp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/ase/phonons.py", line 320, in calculate
    forces = self(atoms_N)
             ^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/ase/phonons.py", line 317, in __call__
    return atoms_N.get_forces()
           ^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/ase/atoms.py", line 788, in get_forces
    forces = self._calc.get_forces(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/ase/calculators/abc.py", line 23, in get_forces
    return self.get_property('forces', atoms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/mace/calculators/mace.py", line 217, in calculate
    out = model(batch.to_dict(), compute_stress=compute_stress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/mace/modules/models.py", line 337, in forward
    node_feats, sc = interaction(
                     ^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/mace/modules/blocks.py", line 613, in forward
    mji = self.conv_tp(
          ^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/e3nn/o3/_tensor_product/_tensor_product.py", line 529, in forward
    return self._compiled_main_left_right(x, y, real_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/home/mmollo/miniconda3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/fx/graph_module/___torch_mangle_11.py", line 97, in forward
    _w3j_1_2_1 = self._w3j_1_2_1
    mul_15 = torch.mul(_w3j_1_2_1, 1.7320508075688772)
    tensordot = _0(einsum_11, mul_15, ([4, 3], [1, 0]), None, )
                ~~ <--- HERE
    einsum_12 = torch.einsum("dbca,dbc->dba", [tensordot, reshape_21])
    reshape_22 = torch.reshape(einsum_12, [getitem_4, 384])
  File "code/__torch__/torch/functional/___torch_mangle_0.py", line 9, in tensordot
  dims_a, dims_b, = dims1
  if torch.__is__(out, None):
    _1 = torch.tensordot(a, b, dims_a, dims_b)
         ~~~~~~~~~~~~~~~ <--- HERE
    _0 = _1
  else:

Traceback of TorchScript, original code (most recent call last):
  File "<eval_with_key>.127", line 75, in forward
    _w3j_1_2_1 = self._w3j_1_2_1
    mul_15 = _w3j_1_2_1 * 1.7320508075688772;  _w3j_1_2_1 = None
    tensordot = torch.functional.tensordot(einsum_11, mul_15, ([4, 3], [1, 0]), out = None);  mul_15 = None
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    einsum_12 = torch.functional.einsum('dbca,dbc->dba', tensordot, reshape_21);  tensordot = reshape_21 = None
    reshape_22 = einsum_12.reshape(getitem_4, 384);  einsum_12 = None
  File "/pscratch/sd/c/cyrusyc/.conda/mace/lib/python3.11/site-packages/torch/functional.py", line 1100, in tensordot

    if out is None:
        return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
               ~~~~~~~~~~~~~ <--- HERE
    else:
        return _VF.tensordot(a, b, dims_a, dims_b, out=out)  # type: ignore[attr-defined]
RuntimeError: CUDA out of memory. Tried to allocate 6.55 GiB. GPU 0 has a total capacty of 31.74 GiB of which 995.62 MiB is free. Including non-PyTorch memory, this process has 30.76 GiB memory in use. Of the allocated memory 29.48 GiB is allocated by PyTorch, and 941.29 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

FINISHED!!!
